name: Flutter Test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  flutter-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (if needed for advanced builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and run tests inside Docker
      - name: Build and Test Flutter App
        uses: docker/build-push-action@v3
        with:
          push: false # No need to push the image
          context: .
          file: ./Dockerfile
          tags: flutter-test:latest
      - name: Run Flutter Tests
        run: |
          docker run --rm flutter-test:latest flutter test
